// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdgqpcedobedkyhjbuku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZ3FwY2Vkb2JlZGt5aGpidWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODgxODUsImV4cCI6MjA1OTQ2NDE4NX0.vC7T9OVRydDdjaDHOJ26uPKwesDM86MPh-jVeOg_yt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);